export const experiences = [
  {
    active: false,
    link: "https://lucky-cement.com",
    title: "Information Technology Intern",
    company_name: "Lucky Cement Ltd.",
    icon: "/companies/luckycement.png",

    iconBg: "white",
    date: "November 2021 - January 2022",
    points: [
      "Worked on SAP ABAP as an intern in the IT department.",
      "Writing queries in ABAP to perform CRUD Operations on the database",
      `Worked on generating reports, building report interfaces and modularizing programs with 'Includes', 'Forms' and 'Function Modules'`,
    ],
  },
  {
    active: false,
    link: "https://tfm.digital/",
    title: "Full Stack Developer",
    company_name: "TFM Digital",
    icon: "/companies/tfmdigital.png",
    iconBg: "#E6DEDD",
    date: "Aug 2022 - Jan 2023",
    points: [
      "Worked as a Full Stack Web Developer, developer multiple web apps with different functionalities.",
      "Performing duties of both front end and back end developer.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    active: false,
    link: "https://www.upwork.com/agencies/1553342477126914048/",
    title: "Web Developer",
    company_name: "EZ Solvers",
    icon: "/companies/ezsolvers.png",
    iconBg: "white",
    date: "Feb 2023 - June 2023",
    points: [
      "Performed duties of web development and SEO optimization.",
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    active: false,
    link: "https://piogcl.com/",
    title: "Graduate Trainee ICT",
    company_name: "Prime International Oil And Gas",
    icon: "/companies/prime.png",
    iconBg: "white",
    date: "Aug 2023 - Jul 2024",
    points: [
      "Worked in the IT Compliance and Governance and Business Application Development department. ",
      "Worked on doing research and writing policies for the company including Cyber Security Policy, Recourse Management Policy.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Developed a Contract Management Tool that keeps progress of active contracts, call-offs, requisitions and generates automated email alerts.",
    ],
  },
  {
    active: true,
    link: "https://www.upwork.com/freelancers/zuhayr",

    title: "Top Rated Full Stack Web Developer",
    company_name: "Upwork - Freelance",
    icon: "/companies/upwork.png",
    iconBg: "white",
    date: "Apr 2025 - Present",
    points: [
      "Collaborated with multiple international clients to build and deploy full-stack web applications using modern technologies like Next.js, React, and Node.js.",
      "Delivered custom dashboards, AI-powered chatbots, e-commerce platforms, and business automation tools tailored to each client’s needs.",
      "Integrated third-party APIs such as Stripe, Clerk, AWS, and Vercel for payments, authentication, and deployment.",
      "Focused on performance, scalability, and maintainability while ensuring responsive design and cross-browser compatibility.",
      "Maintained consistent client satisfaction through clear communication, fast delivery, and clean, production-ready code.",
    ],
  },
];
